version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    hostname: nginx-host
    ports:
      - "8081:80"
    volumes:
      - shared-logs:/var/log/nginx  
    networks:
      - goaccess_net
    restart: always
    depends_on:
      - goaccess
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  goaccess:
    build: ./goaccess
    container_name: goaccess_viewer
    hostname: goaccess-host
    ports:
      - "8082:80"
    volumes:
      - shared-logs:/var/log/nginx  
    networks:
      - goaccess_net
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

volumes:
  shared-logs:
    name: nginx-goaccess-logs

networks:
  goaccess_net:
    driver: bridge
